### ISSUE TITLE
remove light returns unworkable image 

### ISSUE THREAD

**Issue by guyo13** [PacktPublishing/Learn-OpenCV-4-By-Building-Projects-Second-Edition#1]
Hi,

I've been using the same code for removing light (using the division technique) with the supplied `pattern.pgm` file (Chapter 6, I am using OpenCV 4.0.1).

The result is as follows:
![image](https://user-images.githubusercontent.com/28857112/52181119-10933900-27f7-11e9-878c-023d19409445.png)

You can see that in the removedLight window the nut is barely noticeable which obviously causes our threshold to return all ones.

Applying a simple subtraction of `pattern - img` gives a better result but after Extract Features I'm losing the center hole of the nut is this normal? I though that the CCOMP will retain the inner contours, without it the area feature is going to be skewed...
![image](https://user-images.githubusercontent.com/28857112/52181200-26edc480-27f8-11e9-9c7e-6a0627ade633.png)

I'd appreciate your help!

**Comment by guyo13** [comment]
Update:
I was able to resolve the issue from the second screenshot (the simple image subtraction case). Forgot to pass hierarchy to findContours.

The original issue of light removal by division remains though.

**Comment by damiles** [comment]
Hi, sorry to reply so late.

I use the following command: 

```
./bin/Chapter5 ../data/test.pgm ../../Chapter_06/data/pattern.pgm --lightMethod=1
```

And works properly, what is your execute command for light removal division?
