### ISSUE TITLE
Chapter 10,11,12 Build Error

### ISSUE THREAD

**Issue by yyl-20020115** [PacktPublishing/Learn-OpenCV-4-By-Building-Projects-Second-Edition#4]
in CMakefiles.txt files of chatper 10,11,12
should have
  include_directories( ${OpenCV_INCLUDE_DIRS} )
just like in CMakefiles.txt in  Chapter02
otherwise, #include <opencv2/opencv.cpp> can not find on some Ubuntu platform

also, all $OPENCV_ need to be $OpenCV_
so that make can find the correct lib path

**Comment by deepesh-packt** [comment]
Hey @yyl-20020115,
The issue is being resolved, Thanks for highlighting the issue.

Greetings!

**Comment by yyl-20020115** [comment]
You’r welcome.
BR，
Yilin

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: deepesh-packt<mailto:notifications@github.com>
发送时间: 2020年7月15日 18:50
收件人: PacktPublishing/Learn-OpenCV-4-By-Building-Projects-Second-Edition<mailto:Learn-OpenCV-4-By-Building-Projects-Second-Edition@noreply.github.com>
抄送: Yilin Yang<mailto:yyl_20050115@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [PacktPublishing/Learn-OpenCV-4-By-Building-Projects-Second-Edition] Chapter 10,11,12 Build Error (#4)


Hey @yyl-20020115<https://github.com/yyl-20020115>,
The issue is being resolved, Thanks for highlighting the issue.

Greetings!

―
