### ISSUE TITLE
Chapter_02  sample2.cpp open defalut camera failed

### ISSUE THREAD

**Issue by vk8051** [PacktPublishing/Learn-OpenCV-4-By-Building-Projects-Second-Edition#6]
VideoCapture cap; // open the default camera
	if(videoFile != "")
		cap.open(videoFile);
	else
		cap.open("Recording3.webm");  <<==========Here can not open default camera
    if(!cap.isOpened())  // check if we succeeded
        return -1;

**Comment by ViniGodoy** [comment]
The correct would be 

```cpp
if(videoFile != "")
   cap.open(videoFile);
else
   cap.open(0);
if(!cap.isOpened()) // check if we succeeded
   return -1;
```

**Comment by ViniGodoy** [comment]
Fixed in the source code.
