### ISSUE TITLE
 Ch3 sample2 displayOverlay has error: The library is compiled without QT support

### ISSUE THREAD

**Issue by vk8051** [PacktPublishing/Learn-OpenCV-4-By-Building-Projects-Second-Edition#7]
displayOverlay in Ch3 sample2 

displayOverlay("Lena", "Overlay 5secs", 5000); <<========run in VC2019 will show below error message

OpenCV(4.4.0) Error: The function/feature is not implemented (The library is compiled without QT support) in cv::displayOverlay, file C:\build\master_winpack-build-win64-vc15\opencv\modules\highgui\src\window.cpp, line 572

Does this displayOverlay need QT

**Comment by ViniGodoy** [comment]
Yes, it does. That's why it's in the third chapter called: "Learning Graphical User Interfaces", which is designed to show how to integrate OpenCV and QT for advanced user interfaces. 

Notice that the QT requirement is also on our [chapter readme](Chapter_03).

So, that's not an error.
